<p><a href="<?php echo $this->url('test-action', array('controller' => 'person', 'action'=>'new',));?>">Add new person</a></p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>Department</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($people as $person) : ?>
<tr>
    <td><?php echo $this->escapeHtml($person->getId());?></td>
    <td><?php echo $this->escapeHtml($person->getName());?></td>
    <td><?php echo $this->escapeHtml($person->getDepartment());?></td>
    <td>
        <a href="<?php echo $this->url('test-action', array('controller' => 'person', 'action'=>'edit',))."?id=".$person->getId();?>">Edit</a>
        <a href="<?php echo $this->url('test-action', array('controller' => 'person', 'action'=>'delete',))."?id=".$person->getId();?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>