<p>Follow the steps below to create a new person</p>
<ul>
<?php
if (!$department) {
?>
    <li><a href="<?php echo $this->url().'/department/get?father='.$myAction->getId().'&amp;returnVar=department'; ?>">Get a department</a></li>
<?php
} 
else {
?>  
    <li>You have chosen the department <?php echo $department->getName(); ?>!<a href="<?php echo $this->url().'/department/get?father='.$myAction->getId().'&amp;returnVar=department'; ?>">Choose another?</a></li>
<?php
}
if (!$personFields) {
?>
    <li><a href="<?php echo $this->url().'/person/getFields?father='.$myAction->getId().'&amp;returnVar=personFields'; ?>">Get the person's fields</a></li>
<?php
} 
else {
?>  
    <li>You have defined the person fields: name = <?php echo $personFields['name']; ?>!<a href="<?php echo $this->url().'/person/getFields?father='.$myAction->getId().'&amp;returnVar=personFields'; ?>">Redefine?</a></li>
<?php
}
?>     
</ul>